const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const base = require('./webpack.base.config');
// eslint-disable-next-line import/no-extraneous-dependencies
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const WebpackBuildNotifierPlugin = require('webpack-build-notifier');

const getConfig = (moduleName, port) => ({
  devtool: 'eval-source-map',
  entry: {
    hot: [
      // bundle the client for webpack-dev-server
      // and connect to the provided endpoint
      'react-hot-loader/patch',
      // bundle the client for hot reloading
      // only- means to only hot reload for successful updates
      'webpack/hot/only-dev-server',
      `webpack-dev-server/client?http://0.0.0.0:${port}`,
      // activate HMR for React
    ],
    main: [
      // the entry point of our app
      './src/index.js',
    ],
    vendor1: [
      'react-dom',
      'react-dnd-html5-backend',
      'react-dnd',
    ],
    vendor2: ['react-ace'],
    vendor3: ['moment'],
    vendor4: ['lodash'],
    vendor: [
      'whatwg-fetch',
      'babel-polyfill',
      'immutable',
      'react-redux',
      'react-router-dom',
      'react-router',
      'redux-saga',
      'react',
      'redux',
    ],
  },

  output: {
    path: `${__dirname}/__build__${moduleName || ''}`,
    filename: '[name].[hash].js',
    chunkFilename: '[name].[hash].chunk.js',
    publicPath: '/',
  },
  // target: 'web',
  cache: true,
  recordsPath: path.join(__dirname, 'records.json'),
  module: base,
  resolve: {
    unsafeCache: true,
    extensions: ['.js'],
    alias: {
      src: path.resolve(__dirname, '../src'),
    },
    modules: ['node_modules',
      path.join(__dirname, '../src'),
    ],
    cacheWithContext: false,
  },
  plugins: [
    new WebpackBuildNotifierPlugin({
      title: 'The Lawshram Project - build',
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.SourceMapDevToolPlugin(),
    new webpack.NamedModulesPlugin(),
    new webpack.optimize.CommonsChunkPlugin({
      names: ['main', 'vendor', 'vendor1', 'vendor2', 'vendor3', 'vendor4', 'manifest'], // Specify the common
      // bundle's name.
      minChunks(module) {
        return module.context && module.context.indexOf('node_modules') !== -1;
      },
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest', // Specify the common bundle's name.
      minChunks: Infinity,
    }),
    new ExtractTextPlugin({
      filename: '[name].css',
      allChunks: true,
      disable: true,
      ignoreOrder: true,
    }),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV || 'development'),
      },
    }),
    new HtmlWebpackPlugin({
      template: 'index.html',
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
    }),

    new CopyWebpackPlugin([
      { from: 'src/images/logo.png', to: 'favicon-16x16.png' },
      { from: 'src/images/logo.svg', to: 'favicon-32x32.svg' },
    ], { copyUnmodified: true }),
  ],
  externals: {
    cheerio: 'window',
    'react/addons': true,
    'react/lib/ExecutionEnvironment': true,
    'react/lib/ReactContext': true,
  },
});

module.exports = getConfig;